### ISSUE TITLE
Setting $crumbs_include_home

### ISSUE THREAD

**Issue by andrewhoule** [xini/silverstripe-breadcrumbs#1]
So, I'm not 100% sure if this is an issue or not, but I was having trouble hiding home from the crumbs. I saw there is a $crumbs_include_home boolean on the SiteTreeExtension, and it looks like it's being used in Crumbs, but I've tried setting that via YAML, an extension, and eventually just updating it on SiteTreeExtension directly (just for testing), but it never hid the Home crumb. Am I missing how that works? Or is there an issue there?

Thanks!

**Comment by xini** [comment]
Sorry for this. Just released a fix for this. Cheers.

**Comment by andrewhoule** [comment]
Awesome, thanks!
