### ISSUE TITLE
set config values

### ISSUE THREAD

**Issue by schrattenholz** [xini/silverstripe-breadcrumbs#2]
Hi, I try to set crumbs_include_home and crumbs_show_hidden, but I can not get it working I tried inmy app.yml:

Innoweb\Breadcrumbs\Extensions\SiteTreeExtension:
  crumbs_include_home:
    - true
  crumbs_show_hidden:
    - false
   
Innoweb\Breadcrumbs\Extensions\SiteTreeExtension:
  crumbs_include_home: true
  crumbs_show_hidden: false

**Comment by xini** [comment]
The following config should work:

```
Innoweb\Breadcrumbs\Extensions\SiteTreeExtension:
  crumbs_include_home: true
  crumbs_show_hidden: false
```

Just make sure you have the two spaces before the config values to make it correct yaml.

Can you please test this and let me know how you go?

**Comment by schrattenholz** [comment]
Hej, thanks for quick relpy.

I tried it that way. 2 spaces before the variable 1 is between the colon and the value.
In thy config file I hve several other configuration parameters which work

formatting is awsome ;)

---
Name: sola
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: app

Silverstripe\SiteConfig\SiteConfig:
  extensions:
    - CustomSiteConfig
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - BasicExtension
Sola\HomePage:
  extensions:
    - Schrattenholz\ContentObject\ContentObjectExtension
Page:
  extensions:
    - Schrattenholz\ContentObject\ContentObjectExtension
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - vendor/schrattenholz/contentobject/font/css/fontawesome.css
Innoweb\Breadcrumbs\Extensions\SiteTreeExtension:
  crumbs_include_home: true
  crumbs_show_hidden: false
---
Name: my-project-assetsflysystem
After: '#assetsflysystem'
---
# SilverStripe 4.4 changes the way files are resolved. `silverstripe-assets` resolves files using a variety of formats
# by default. When starting a brand new project on SilverStripe 4.4 or greater, those extra formats are not needed and
# will slowdown file resolution requests a bit. This config removes those redundant formats.
SilverStripe\Core\Injector\Injector:
  # Define public resolution strategy
  SilverStripe\Assets\FilenameParsing\FileResolutionStrategy.public:
    class: SilverStripe\Assets\FilenameParsing\FileIDHelperResolutionStrategy
    properties:
      ResolutionFileIDHelpers:
        - '%$SilverStripe\Assets\FilenameParsing\HashFileIDHelper'
      DefaultFileIDHelper: '%$SilverStripe\Assets\FilenameParsing\NaturalFileIDHelper'
      VersionedStage: Live
  # Define protected resolution strategy
  SilverStripe\Assets\FilenameParsing\FileResolutionStrategy.protected:
    class: SilverStripe\Assets\FilenameParsing\FileIDHelperResolutionStrategy
    properties:
      DefaultFileIDHelper: '%$SilverStripe\Assets\FilenameParsing\HashFileIDHelper'
      ResolutionFileIDHelpers:
        - '%$SilverStripe\Assets\FilenameParsing\HashFileIDHelper'
      VersionedStage: Stage

**Comment by xini** [comment]
The two spaces need to be at the start of the line (indentation). After the colon one is enough. I can't see in your comment what the formating is in your file. 
Have a look at the examples on https://docs.silverstripe.org/en/4/developer_guides/configuration/configuration/ and check out the generic yaml syntax. In Silverstripe indentation in yaml uses two spaces.
